name: Pull Request Tests
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  windows-test:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true

      - uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
        with:
          dotnet-version: 9

      - run: |
          & (Join-Path 'assets' 'install-mecab.ps1')
          Add-Content -Path $Env:GITHUB_PATH -Value (Join-Path $Env:programfiles 'MeCab' 'bin')

      - run: |
          dotnet run --project src --libs
